language: java

env:
  - COMISION=10

jobs:
  include:
    - stage: clean
      script: ./gradlew clean
    - stage: test
      script: ./gradlew test
    - stage: build
      script: ./gradlew build
    - stage: asseble
      script: ./gradlew assemble
